<?php
require_once("../../generalp.config.inc.php");
require_once("../libs/php/adodb5/adodb.inc.php");
require_once("../libs/php/configuracion/config.php");
require_once("../libs/php/clases/ConexionComun.php");
require_once("../libs/php/clases/Menu.php");
require_once("../libs/php/clases/parametrosgenerales.php");
require_once("../libs/php/clases/comunes.php");
require_once("../libs/php/ajax/numerosALetras.class.php");
require_once("../libs/php/clases/Mensajes.php");
?>
