<?php

include("../../libs/php/clases/vendedor.php");
$vendedor = new Vendedor();


if(isset($_POST["opt_subseccion"])){

$instruccion = "
INSERT INTO `vendedor` (
`cod_vendedor`,
`nombre`,
`direccion1`,
`direccion2`,
`telefonos`,
`fax`,
`email`,
`clase`,
`venta_x_debajo_minimo`,
`venta_a_precio1`,
`venta_a_precio2`,
`venta_a_precio3`,
`venta_x_servicio`,
`venta_gerericos`,
`comision_x_debajo_minimo`,
`comision_a_precio1`,
`comision_a_precio2`,
`comision_a_precio3`,
`comision_x_servicio`,
`comision_gerericos`,
`comision_tabla_de_cobros`,
`tipo_comision`,
`rancoshasta1`,
`rancosdesde1`,
`rancosdesde2`,
`rancoshasta2`,
`rancosdesde3`,
`rancoshasta3`,
`rancosdesde4`,
`rancoshasta4`,
`rancosdesde5`,
`rancoshasta5`,
`factor1`,
`factor2`,
`factor3`,
`factor4`,
`factor5`,
`comision_tabla_de_cobrosven`,
`tipo_comisionven`,
`ranvenhasta1`,
`ranvendesde1`,
`ranvendesde2`,
`ranvenhasta2`,
`ranvendesde3`,
`ranvenhasta3`,
`ranvendesde4`,
`ranvenhasta4`,
`ranvendesde5`,
`ranvenhasta5`,
`factor1ven`,
`factor2ven`,
`factor3ven`,
`factor4ven`,
`factor5ven`) VALUES (
 NULL,
'".$_POST["nombre"]."',
'".$_POST["direccion1"]."',
'".$_POST["direccion2"]."',
'".$_POST["telefonos"]."',
'".$_POST["fax"]."',
'".$_POST["email"]."',
'".$_POST["clase"]."',
'".$_POST["venta_x_debajo_minimo"]."',
'".$_POST["venta_a_precio1"]."',
'".$_POST["venta_a_precio2"]."',
'".$_POST["venta_a_precio3"]."',
'".$_POST["venta_x_servicio"]."',
'".$_POST["venta_gerericos"]."',
'".$_POST["comision_x_debajo_minimo"]."',
'".$_POST["comision_a_precio1"]."',
'".$_POST["comision_a_precio2"]."',
'".$_POST["comision_a_precio3"]."',
'".$_POST["comision_x_servicio"]."',
'".$_POST["comision_gerericos"]."',
'".$_POST["comision_tabla_de_cobros"]."',
'".$_POST["tipo_comision"]."',
'".$_POST["rancoshasta1"]."',
'".$_POST["rancosdesde1"]."',
'".$_POST["rancosdesde2"]."',
'".$_POST["rancoshasta2"]."',
'".$_POST["rancosdesde3"]."',
'".$_POST["rancoshasta3"]."',
'".$_POST["rancosdesde4"]."',
'".$_POST["rancoshasta4"]."',
'".$_POST["rancosdesde5"]."',
'".$_POST["rancoshasta5"]."',
'".$_POST["factor1"]."',
'".$_POST["factor2"]."',
'".$_POST["factor3"]."',
'".$_POST["factor4"]."',
'".$_POST["factor5"]."',
'".$_POST["comision_tabla_de_cobrosven"]."',
'".$_POST["tipo_comisionven"]."',
'".$_POST["ranvenhasta1"]."',
'".$_POST["ranvendesde1"]."',
'".$_POST["ranvendesde2"]."',
'".$_POST["ranvenhasta2"]."',
'".$_POST["ranvendesde3"]."',
'".$_POST["ranvenhasta3"]."',
'".$_POST["ranvendesde4"]."',
'".$_POST["ranvenhasta4"]."',
'".$_POST["ranvendesde5"]."',
'".$_POST["ranvenhasta5"]."',
'".$_POST["factor1ven"]."',
'".$_POST["factor2ven"]."',
'".$_POST["factor3ven"]."',
'".$_POST["factor4ven"]."',
'".$_POST["factor5ven"]."' );";
    
 $vendedor->Execute2($instruccion);
 header("Location: ?opt_menu=".$_POST["opt_menu"]."&opt_seccion=".$_POST["opt_seccion"]);
}

?>
